language: ruby

services:
  - postgresql

before_install:
  - gem install bundler

script:
  - RACK_ENV=test rake db:migrate --trace
  - bundle exec rspec

after_script:
  - bundle exec rake coveralls:push