require "sinatra/base"
require "sinatra/config_file"

class MyApp < Sinatra::Base
register Sinatra::ConfigFile

config_file 'path/to/config.yml'

get '/' do
# Configurations
end

  # Modular application code
end