development:
  adapter: postgresql
  encoding: unicode
  database: mla
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: mla_test
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: 
