development:
  adapter: postgresql
  encoding: unicode
  database: mla
  pool: 2
  username: dmwangi
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: mla_test
  pool: 2
  username: dmwangi
  password: 
