development:
  adapter: postgresql
  encoding: unicode
  database: <% ENV['DB_NAME'] %>
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: <% ENV['TEST_DB_NAME'] %>
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: 
