production:
  adapter: postgresql
  encoding: unicode
  host: <% ENV['DB_HOST'] %>
  database: C
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: <% ENV['DB_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mla
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: <% ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mla_test
  pool: 2
  username: <% ENV['DB_USERNAME'] %>
  password: <% ENV['DB_PASSWORD'] %>
